config/routes.rb
Menu::Application.routes.draw do
  mount BrowseEverything::Engine => '/browse'

  devise_for :users
  resources :new_records do
    member do
      post  'save_xml'
      post  'publish'
    end
  end

  get 'jobs/browse' => 'jobs#browse'
  resources :jobs

  root 'jobs#index'
  get 'existing_records/edit', to: 'existing_records#edit', as: :existing_records_edit
  post 'existing_records/update/' => 'existing_records#update'
  post 'jobs/import' => 'jobs#import'
  post 'existing_records/save_xml/:pid', to: 'existing_records#save_xml', as: :existing_records_save_xml

end

app/models/new_record.rb
class NewRecord < ActiveRecord::Base
  belongs_to :job

  has_attached_file :proxy, :styles => { :thumb => [ "100x100", :jpg ], :original => ["1000x1000", :jpg] }

  before_create :add_minimal_xml

  include Validator

  validates_attachment_content_type :proxy, :content_type => "image/tiff"
  validates :job_id, :presence => true
  validates :filename, :uniqueness => true


  def job_id_display
    self.job.job_id
  end

  def path
    "#{location}/#{filename}"
  end

  def valid_vra?
    true if validate_vra.empty?
  end

  def validate_vra
    doc = Nokogiri::XML(self.xml)

    invalid = []
    XSD.validate(doc).each do |error|
      invalid << "Validation error: #{error.message}"
    end
    required_fields = validate_required_fields(doc)
    invalid << required_fields unless required_fields.nil?

    invalid
  end

  private

  def add_minimal_xml
    self.xml = Nokogiri::XML.parse(File.read( "#{Rails.root}/app/assets/xml/vra_minimal.xml" )) if self.xml.nil?
  end

end

app/controllers/new_records_controller.rb
require 'rest-client'

class NewRecordsController < ApplicationController
  before_action :set_new_record, only: [:show, :edit, :update, :destroy, :save_xml, :publish]
  layout "new_records"

  # GET /new_records
  # GET /new_records.json
  def index
    @new_records = NewRecord.all
  end

  # GET /new_records/1
  # GET /new_records/1.json
  def show
    respond_to do |format|
      format.html
      format.xml { render xml: @new_record.xml }
    end
  end

  # GET /new_records/new
  def new
    @new_record = NewRecord.new
  end

  # GET /new_records/1/edit
  def edit
  end


  # PATCH/PUT /new_records/1
  # PATCH/PUT /new_records/1.json
  def update
    respond_to do |format|
      if @new_record.update_attributes(new_record_params)
        format.html { redirect_to @new_record, notice: 'New Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @new_record.errors, status: :unprocessable_entity }
      end
    end
  end


  # POST /new_records
  # POST /new_records.json
  def create
    @new_record = NewRecord.new(new_record_params)
    respond_to do |format|
      if @new_record.save
        format.html { redirect_to @new_record, notice: 'New record was successfully created.' }
        format.json { render action: 'show', status: :created, location: @new_record }
      else
        format.html { render action: 'new' }
        format.json { render json: @new_record.errors, status: :unprocessable_entity }
      end
    end
  end


  # POST /new_records/1.xml
  def save_xml
    @new_record.xml = request.body.read
    respond_to do |format|
      if @new_record.save
        format.xml { redirect_to @new_record, notice: 'New Record was successfully updated.'  }
      else
        format.xml { render xml: @new_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /new_records/1
  # DELETE /new_records/1.json
  def destroy
    @new_record.destroy
    respond_to do |format|
      format.html { redirect_to !request.referer.nil? ? request.referer : new_records_url }
      format.json { head :no_content }
    end
  end

  def publish
    @new_record.xml = request.body.read

    if @new_record.save
      @new_record.xml = TransformXML.prepare_vra_xml( @new_record.xml, @new_record.filename )
      @accession_nbr = TransformXML.get_accession_nbr( @new_record.xml )

      if @new_record.valid_vra?
        response = dil_multiresimages_post( @new_record.xml, @new_record.path, @accession_nbr )
        response_xml_doc = Nokogiri::XML( response )

        logger.info("response: #{response}")

        if response_xml_doc.at_xpath( '//pid' ) && /Publish successful/.match(response_xml_doc)
          @new_record.destroy
          job_url = "#{root_url}jobs/#{@new_record.job_id}"

          render json: {:localName => job_url}
        else
          flash_messages = [ response_xml_doc.at_xpath( '//description' ).text.truncate( 50 ) ]
          flash_messages << "New Record not published"
          flash[:error] = flash_messages
          render :template => "new_records/edit", :status => 400
        end
      else
        errors = @new_record.validate_vra
        flash[:error] = errors
        render :template => "new_records/edit", :status => 400
      end
    else
      render edit: @new_record.errors, status: :unprocessable_entity
    end
end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_new_record
      @new_record = NewRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def new_record_params
      params.require(:new_record).permit(:filename, :location, :proxy, :job_id)
    end

    def dil_multiresimages_post( xml, path, accession_nbr )
      RestClient::Resource.new(
        MENU_CONFIG["dil_url"],
        verify_ssl: OpenSSL::SSL::VERIFY_NONE,

      ).post xml: xml , path: path , accession_nbr: accession_nbr, from_menu: true
    end

end

app/views/new_records/_form.html.erb
<%= form_for(@new_record) do |f| %>
  <div class="field">
    <%= f.label :filename %><br>
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/new_records/edit.html.erb
<h1>VRA Editor</h1>

<div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#editor" aria-controls="editor" role="tab" data-toggle="tab">Editor</a></li>
    <li role="presentation"><a href="#image" aria-controls="image" role="tab" data-toggle="tab">Image</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">

    <!-- Editor tab -->
    <div role="tabpanel" class="tab-pane active" id="editor">
      <div class="row">
        <div class="col-lg-11">

          <div id="xml_editor">
            <vra:vra xmlns:vra="http://www.vraweb.org/vracore4.htm"></vra:vra>
          </div>
        </div>
      </div>

      <!-- Publish button and image thumbnail -->
      <div id="persistData">
        <div id="publishButton">
          <div id='publishUrl' class='btn btn-primary' data-url="<%= publish_new_record_path(@new_record) %>">Publish</div>
        </div>
        <%= image_tag @new_record.proxy( "thumb" ), class: "thumbnail thumb" %>
      </div>
    </div>

    <!-- Image tab -->
    <div role="tabpanel" class="tab-pane" id="image">
      <div class="row">
        <div class="col-lg-6">
          <%= image_tag @new_record.proxy( "original" ), class: "img-responsive thumbnail original" %>
        </div>
        <div class="col-lg-6">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  var xmlUploadConfig = [
   {id: "defaultUrl", createDomElement: true, cssClass: 'send_xml', linkText: 'Save', url: "<%= save_xml_new_record_path(@new_record) %>"},
   {id: "publishUrl", createDomElement: false, url: '<%= publish_new_record_path(@new_record) %>'}
   ]


  $(function() {

    function publishSuccess(response){
      if ($("#errors").is(":visible")){
        $("#errors").hide();
      }

      if ($(".xml_submit_status").hasClass("alert alert-danger")){
        $(".xml_submit_status").removeClass("alert alert-danger");
      }
      if (response.localName){
        document.location.href = response.localName;
      }
    }

    function publishError(jqXHR){
      $(".xml_submit_status").addClass("alert alert-danger");
      $(".xml_submit_status").html("Errors! This record was not published. Details above.");
      var msg = jqXHR.getResponseHeader('X-Message');
      if ($(".container").children("#errors").length == 0){
        $(".container").prepend("<div id='errors' class='alert alert-danger'></div>");
        $('#errors').html("<p>" + msg + "</p>");
      } else {
        $('#errors').html("<p>" + msg + "</p>");
      }
    }

    var extractor = new Xsd2Json("vra-both.xsd", {"schemaURI":"<%= root_path %>"});

    $("#xml_editor").xmlEditor({
      ajaxOptions: {
        xmlRetrievalPath: "<%= url_for(:only_path => false, :controller => 'new_records', :action => 'show', :id => @new_record.id, :format => :xml) %>"
      },
      submitButtonConfigs: [
          {
          id: "publishUrl",
          createDomElement: false,
          //onSubmit: submitThis,
          url: '<%= publish_new_record_path(@new_record) %>',
          responseHandler: publishSuccess,
          errorHandler: publishError
        },
          {
          id: "defaultUrl",
          createDomElement: true,
          cssClass: 'send_xml',
          label: 'Save',
          url: "<%= save_xml_new_record_path(@new_record) %>",
          //submitHandler: submitThis,
          responseHandler: publishSuccess,
          errorHandler: publishError
          }
      ],
      schema: extractor.getSchema(),
      documentStatusPanelDomId: "#persistData"
    });

  });
</script>

app/views/new_records/index.html.erb
<h1>Listing new records</h1>

<table class="table">
  <thead class="header">
    <tr>
      <th>Thumbnail</th>
      <th>Filename</th>
      <th>Job ID</th>
      <th colspan=3></th>
    </tr>
  </thead>

  <tbody>
    <% @new_records.each do |new_record| %>
      <tr class="new-record-entry">
        <td><%= image_tag new_record.proxy( :thumb ), class: "thumbnail" %></td>
        <td><%= new_record.filename %></td>
        <td><%= new_record.job_id_display %></td>
        <td><%= link_to 'Show', new_record, class: "btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_new_record_path(new_record), class: "btn btn-default" %></td>
        <td><%= link_to 'Delete', new_record, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_new_record_path, class: "btn btn-default" %>

app/views/new_records/new.html.erb
<h1>New record</h1>

<%= render 'form' %>

<%= link_to 'Back', new_records_path %>

app/views/new_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @new_record.filename %>
</p>

<p>
  <strong>Location:</strong>
  <%= @new_record.location %>
</p>

<%= link_to 'Edit', edit_new_record_path(@new_record) %> |
<%= link_to 'Back', new_records_path %>