config/routes.rb
Menu::Application.routes.draw do
  mount BrowseEverything::Engine => '/browse'

  devise_for :users
  resources :new_records do
    member do
      post  'save_xml'
      post  'publish'
    end
  end

  get 'jobs/browse' => 'jobs#browse'
  resources :jobs

  root 'jobs#index'
  get 'existing_records/edit', to: 'existing_records#edit', as: :existing_records_edit
  post 'existing_records/update/' => 'existing_records#update'
  post 'jobs/import' => 'jobs#import'
  post 'existing_records/save_xml/:pid', to: 'existing_records#save_xml', as: :existing_records_save_xml

end

app/models/existing_record.rb
class ExistingRecord < ActiveRecord::Base
	
	include Validator

	def valid_vra?
    true if validate_vra.empty?
  end

  def validate_vra
    doc = Nokogiri::XML(self.xml)

    invalid = []
    XSD.validate(doc).each do |error|
      invalid << "Validation error: #{error.message}"
    end

    missing_fields = validate_required_fields(doc)
    invalid << missing_fields unless missing_fields.nil?

    missing_or_invalid = invalid.reject do |error|
      error.include?("inu:dil") 
    end
    missing_or_invalid
  end

end

app/controllers/existing_records_controller.rb
require 'rest-client'

class ExistingRecordsController < ApplicationController

  # GET /existing_records/1/edit
  def edit
    @existing_record = ExistingRecord.where(pid: params[:pid]).first_or_create
    if @existing_record.xml.blank?
      begin
        @existing_record.xml = dil_api_get_vra( params[:pid] )
      rescue
        flash[:error] = "The pid: \"#{params[:pid]}\" was not found in Repository|Images"
        redirect_to root_path
      end
    end
  end

  # PATCH/PUT /existing_records/1
  # PATCH/PUT /existing_records/1.json
  def update
    pid = params[:pid]
    @existing_record = ExistingRecord.find_by_pid(pid)
  	doc = Nokogiri::XML.parse( request.body.read )
    # do we have to remove the display if it's there?

    if doc.children.first.keys.include?('prefix')
      doc.children.first.delete('prefix')
    end


    #also, some of the records in fedora datastream don't seem to be in xml.
    #what then? fail? convert it? might not be valid record!!
    @existing_record.xml = doc
    if @existing_record.valid_vra?

  	 resp = dil_api_update_image( pid, doc.children )
      if resp.include?("Error")
        render action: 'edit', :pid => pid, :status => 400
      else
        @existing_record.save
        render json: {:localName => "#{root_url}"}
      end
    else
      errors = @existing_record.validate_vra
      flash[:error] = errors
      render action: 'edit', :pid => pid, :status => 400
    end
  end

  # POST /existing_records/1.xml
  def save_xml
    @existing_record = ExistingRecord.where(pid: params[:pid]).first_or_create
    @existing_record.xml = request.body.read
    respond_to do |format|
      if @existing_record.save
        format.xml { redirect_to action: "edit", pid: params[:pid],  notice: 'Record was successfully updated.'  }
      else
        format.xml { render xml: edit.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def dil_api_get_vra( pid )
      RestClient::Resource.new(
        "#{MENU_CONFIG["dil_img_service"]}/technical_metadata/#{pid}/VRA",
        verify_ssl: OpenSSL::SSL::VERIFY_NONE
      ).get
    end

    def dil_api_update_image( pid, xml )
      RestClient::Resource.new(
        MENU_CONFIG["dil_update"],
        verify_ssl: OpenSSL::SSL::VERIFY_NONE
      ).put({pid: pid, xml: xml})
    end

end

app/views/existing_records/edit.html.erb
<h1>VRA Editor</h1>

<div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#editor" aria-controls="editor" role="tab" data-toggle="tab">Editor</a></li>
    <li role="presentation"><a href="#image" aria-controls="image" role="tab" data-toggle="tab">Image</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">

    <!-- Editor tab -->
    <div role="tabpanel" class="tab-pane active" id="editor">
      <div class="row">
        <div class="col-lg-11">
        <textarea id="xml_editor"><%= @existing_record.xml %></textarea>
        </div>
      </div>


      <!-- Publish button and image thumbnail -->
      <div id="persistData">
        <div id="publishButton">
          <div id='publishUrl' class='btn btn-primary' data-url="<%= existing_records_update_path(:pid => @existing_record.pid) %>">Publish</div>
        </div>
        <%= image_tag(get_repo_image(@existing_record.pid, 120), class: 'thumbnail thumb') %>
      </div>
    </div>

    <!-- Image tab -->
    <div role="tabpanel" class="tab-pane" id="image">
      <div class="row">
        <div class="col-lg-12">
          <%= image_tag(get_repo_image(@existing_record.pid, 900), class: 'thumbnail thumb') %>
        </div>
      </div>
    </div>

  </div>

</div>

<script>
  var xmlUploadConfig = [
   {id: "defaultUrl", createDomElement: true, cssClass: 'send_xml', linkText: 'Save', url: "<%= existing_records_save_xml_path(@existing_record.pid) %>"}]

  $(function() {

    function publishSuccess(response){
      if ($("#errors").is(":visible")){
        $("#errors").hide();
      }

      if ($(".xml_submit_status").hasClass("alert alert-danger")){
        $(".xml_submit_status").removeClass("alert alert-danger");
      }
      if (response.localName){
        document.location.href = response.localName;
      }
    }

    function publishError(jqXHR){
      $(".xml_submit_status").addClass("alert alert-danger");
      $(".xml_submit_status").html("Errors! This record was not published. Details above.");
      var msg = jqXHR.getResponseHeader('X-Message');
      if ($(".container").children("#errors").length == 0){
        $(".container").prepend("<div id='errors' class='alert alert-danger'></div>");
        $('#errors').html("<p>" + msg + "</p>");
      } else {
        $('#errors').html("<p>" + msg + "</p>");
      }
    }

    var extractor = new Xsd2Json("vra-both.xsd", {"schemaURI":"<%= root_path %>"});

    $("#xml_editor").xmlEditor({
      schema: extractor.getSchema(),
      documentStatusPanelDomId: "#persistData",
      submitButtonConfigs: [{
          id: "publishUrl",
          createDomElement: false,
          //onSubmit: submitThis,
          url: '<%= existing_records_update_path(:pid => @existing_record.pid) %>',
          responseHandler: publishSuccess,
          errorHandler: publishError
        },
        {
          id: "defaultUrl",
          createDomElement: true,
          cssClass: 'send_xml',
          label: 'Save',
          url: "<%= existing_records_save_xml_path(:pid => @existing_record.pid) %>",
          responseHandler: publishSuccess,
          errorHandler: publishError
        }
      ]
    });

  });
</script>