config/routes.rb
Menu::Application.routes.draw do
  mount BrowseEverything::Engine => '/browse'

  devise_for :users
  resources :new_records do
    member do
      post  'save_xml'
      post  'publish'
    end
  end

  get 'jobs/browse' => 'jobs#browse'
  resources :jobs

  root 'jobs#index'
  get 'existing_records/edit', to: 'existing_records#edit', as: :existing_records_edit
  post 'existing_records/update/' => 'existing_records#update'
  post 'jobs/import' => 'jobs#import'
  post 'existing_records/save_xml/:pid', to: 'existing_records#save_xml', as: :existing_records_save_xml

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag("brand.png", alt: "Brand") %>
      <% end %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= form_tag(existing_records_edit_path, method: "get", class: "navbar-form navbar-left") do %>
        <div class="form-group">
          <%= text_field_tag(:pid, params[:pid], placeholder: "Enter identifier...", class: "form-control", id: "pid-field", required: "required") %>
        </div>
        <%= submit_tag "Search", :name => nil, id: "search-button", class: "btn btn-default" %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if current_page?(jobs_browse_path) %>">
          <%= link_to('Import Images', jobs_browse_path) %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Resources<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Help Document", "https://share.northwestern.edu/dept/LIB/rdc/Procedures/MENU%20help.aspx", :target => "_blank" %></li>
            <li><%= link_to "Cataloging Guidelines", "https://share.northwestern.edu/dept/LIB/rdc/Procedures/Cataloging%20Guidelines.aspx", :target => "_blank" %></li>
          </ul>
        </li>
        <% if user_signed_in? %>
          <li>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Menu - <%= "#{Rails.env}" %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">
    <div class="alert alert-notice">
      <%= flash_messages %>
    </div>
  </div>

  <div class="container-fluid">
    <%= yield %>
  <%= debug(params) if Rails.env.development? %>
  <%= "Server restarted at: " + Menu::Application.config.build_identifier if Rails.env.development? || Rails.env.staging? %>
  </div>
</body>
</html>

app/views/layouts/new_records.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Menu - <%= "#{Rails.env}" %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">
    <%= flash_messages %>
  </div>

  <div class="container-fluid">
    <%= yield %>
  <%= debug(params) if Rails.env.development? %>
  <%= "Server restarted at: " + Menu::Application.config.build_identifier if Rails.env.development? || Rails.env.staging? %>
  </div>
</body>
</html>